import { Song } from "./song";

export const songs: Song[] = [
  {
    id: 1,
    title: "Chaos Theory",
    artist: "GRiZ & Wooli",
    artwork: require("../assets/songs/chaos_theory.jpg"),
    audio: require("../assets/audio/chaos_theory.m4a"),
  },
  {
    id: 2,
    title: "Night Terrors",
    artist: "Hyper Potions, Boom Kitty & CHOMPO",
    artwork: require("../assets/songs/night_terrors.jpg"),
    audio: require("../assets/audio/night_terrors.m4a"),
    video: require("../assets/videos/night_terrors.mp4"),
  },
  {
    id: 3,
    title: "Slash Inferno",
    artist: "Waterflame, Teminite & Boom Kitty",
    artwork: require("../assets/songs/slash_inferno.jpg"),
    audio: require("../assets/audio/slash_inferno.m4a"),
  },
  {
    id: 4,
    title: "PLAY (VIP)",
    artist: "Tokyo Machine",
    artwork: require("../assets/songs/play.jpg"),
    audio: require("../assets/audio/play.m4a"),
  },
  {
    id: 5,
    title: "KURSE OF KHARTOUM",
    artist: "Boom Kitty, Tanger & CHOMPO",
    artwork: require("../assets/songs/kurse.jpg"),
    audio: require("../assets/audio/kurse.m4a"),
  },
  {
    id: 6,
    title: "Rapid Fire (Ft. Eksman)",
    artist: "Excision, Wooli & Ganja White Night",
    artwork: require("../assets/songs/rapid_fire.jpg"),
    audio: require("../assets/audio/rapid_fire.m4a"),
  },
  {
    id: 7,
    title: "DABADABADABADABA",
    artist: "Excision & Dion Timmer",
    artwork: require("../assets/songs/daba.jpg"),
    audio: require("../assets/audio/daba.m4a"),
  },
  {
    id: 8,
    title: "Danger",
    artist: "Teminite & Boom Kitty",
    artwork: require("../assets/songs/danger.jpg"),
    audio: require("../assets/audio/danger.m4a"),
  },
  {
    id: 9,
    title: "BUSTED",
    artist: "Tokyo Machine, Boom Kitty & Teminite",
    artwork: require("../assets/songs/busted.jpg"),
    audio: require("../assets/audio/busted.m4a"),
  },
  {
    id: 10,
    title: "Heave Ho",
    artist: "Boom Kitty & Teminite",
    artwork: require("../assets/songs/heave_ho.jpg"),
    audio: require("../assets/audio/heave_ho.m4a"),
  },
  {
    id: 11,
    title: "Desperate",
    artist: "NEFFIX & Tokyo Machine",
    artwork: require("../assets/songs/desperate.jpg"),
    audio: require("../assets/audio/desperate.m4a"),
  },
  {
    id: 12,
    title: "Stitches",
    artist: "Tokyo Machine & Guy Arthur",
    artwork: require("../assets/songs/stitches.jpg"),
    audio: require("../assets/audio/stitches.m4a"),
  },
  {
    id: 13,
    title: "MOSHI",
    artist: "Tokyo Machine",
    artwork: require("../assets/songs/moshi.jpg"),
    audio: require("../assets/audio/moshi.m4a"),
  },
  {
    id: 14,
    title: "POWERSOUND",
    artist: "ELEPS",
    artwork: require("../assets/songs/powersound.jpg"),
    audio: require("../assets/audio/powersound.m4a"),
  },
  {
    id: 15,
    title: "SLASH",
    artist: "Tokyo Machine",
    artwork: require("../assets/songs/slash.jpg"),
    audio: require("../assets/audio/slash.m4a"),
  },
  {
    id: 16,
    title: "Virtual Gaming (Tokyo Machine Remix)",
    artist: "Naeleck, Hige Driver, Tokyo Machine",
    artwork: require("../assets/songs/virtual_gaming.jpg"),
    audio: require("../assets/audio/virtual_gaming.m4a"),
  },
  {
    id: 17,
    title: "GALACTICAL",
    artist: "Tokyo Machine",
    artwork: require("../assets/songs/galactical.jpg"),
    audio: require("../assets/audio/galactical.m4a"),
  },
  {
    id: 18,
    title: "HOT SHOT",
    artist: "Tokyo Machine",
    artwork: require("../assets/songs/hot_shot.jpg"),
    audio: require("../assets/audio/hot_shot.m4a"),
  },
  {
    id: 19,
    title: "WATCH OUT!",
    artist: "Tokyo Machine & Guy Arthur",
    artwork: require("../assets/songs/watch_out.jpg"),
    audio: require("../assets/audio/watch_out.m4a"),
  },
  {
    id: 20,
    title: "KNOCKOUT",
    artist: "Tokyo Machine & MDK",
    artwork: require("../assets/songs/knockout.jpg"),
    audio: require("../assets/audio/knockout.m4a"),
  },
  {
    id: 21,
    title: "Mortals (Tokyo Machine & Boom Kitty Remix)",
    artist: "Warriyo, Tokyo Machine & Boom Kitty",
    artwork: require("../assets/songs/mortals.jpg"),
    audio: require("../assets/audio/mortals.m4a"),
  },
  {
    id: 22,
    title: "PH4NTOM",
    artist: "HAUNTY",
    artwork: require("../assets/songs/ph4ntom.jpg"),
    audio: require("../assets/audio/ph4ntom.m4a"),
  },
  {
    id: 23,
    title: "Rattlesnake",
    artist: "Rogue",
    artwork: require("../assets/songs/rattlesnake.jpg"),
    audio: require("../assets/audio/rattlesnake.m4a"),
  },
  {
    id: 24,
    title: "Immortal",
    artist: "Slippy",
    artwork: require("../assets/songs/immortal.jpg"),
    audio: require("../assets/audio/immortal.m4a"),
  },
  {
    id: 25,
    title: "GHOSTY",
    artist: "Tokyo Machine & Boom Kitty",
    artwork: require("../assets/songs/ghosty.jpg"),
    audio: require("../assets/audio/ghosty.m4a"),
  },
  {
    id: 26,
    title: "CRANK",
    artist: "Tokyo Machine",
    artwork: require("../assets/songs/crank.jpg"),
    audio: require("../assets/audio/crank.m4a"),
  },
  {
    id: 27,
    title: "FAR OUT - VIP",
    artist: "Tokyo Machine",
    artwork: require("../assets/songs/far_out_vip.jpg"),
    audio: require("../assets/audio/far_out_vip.m4a"),
  },
  {
    id: 28,
    title: "Alone",
    artist: "Marshmello",
    artwork: require("../assets/songs/alone.jpg"),
    audio: require("../assets/audio/alone.m4a"),
  },
];
